version: "3"

services:
  app:
    build: .
    privileged: true
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  bundle:
  redis:
